### ISSUE TITLE
nil errors in getWishlistData on first load

### ISSUE THREAD

**Issue by hurtstotouchfire** [howaboutudance/wishlist-total#2]
https://github.com/hurtstotouchfire/wishlist-total/blob/master/js/background.js#L101 chokes on some initial case, like, the first time you load the extension and hit an amazon wishlist. Will try replicating.

Are you still interested in updating this? If not, I may just diverge and restructure things according to my preferences.

**Comment by howaboutudance** [comment]
knock yourself out
